In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('insurance_data.csv')
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']], df.bought_insurance, test_size=0.2, random_state=25)

In [4]:
X_train
len(X_train)

22

In [5]:
X_test
len(X_test)

6

In [6]:
y_train

0     0
13    0
6     0
17    1
24    1
19    0
25    1
16    1
20    0
3     0
7     1
1     0
5     1
27    0
8     1
18    0
12    0
23    1
22    1
15    1
26    0
4     1
Name: bought_insurance, dtype: int64

In [7]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy() 
X_test_scaled['age'] = X_test_scaled['age']/100

In [8]:
model = keras.Sequential([
  keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=2000)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Epoch 1/2000


2022-12-19 16:02:34.423971: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-12-19 16:02:34.424087: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-12-19 16:02:34.547001: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1/1 [==============================] - 0s 350ms/step - loss: 0.7113 - accuracy: 0.5000
Epoch 2/2000


2022-12-19 16:02:34.714177: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 11ms/step - loss: 0.7110 - accuracy: 0.5000
Epoch 3/2000
1/1 [==============================] - 0s 9ms/step - loss: 0.7106 - accuracy: 0.5000
Epoch 4/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.7102 - accuracy: 0.5000
Epoch 5/2000
1/1 [==============================] - 0s 12ms/step - loss: 0.7098 - accuracy: 0.5000
Epoch 6/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.7094 - accuracy: 0.5000
Epoch 7/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.7091 - accuracy: 0.5000
Epoch 8/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.7087 - accuracy: 0.5000
Epoch 9/2000
1/1 [==============================] - 0s 11ms/step - loss: 0.7083 - accuracy: 0.5000
Epoch 10/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.7079 - accuracy: 0.5000
Epoch 11/2000
1/1 [==============================] - 0s 10ms/step - loss: 0.7076 - accuracy: 0.5000
Epoch 12/2000
1/1 [===

In [9]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 133ms/step - loss: 0.5147 - accuracy: 0.6667


2022-12-19 16:03:04.729799: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


[0.5147147178649902, 0.6666666865348816]

In [10]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [11]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 46ms/step


2022-12-19 16:03:04.912193: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


array([[0.6610701 ],
       [0.51496345],
       [0.32312733],
       [0.56699324],
       [0.67040366],
       [0.7234577 ]], dtype=float32)

In [12]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [14]:
coef, intercept = model.get_weights()
coef, intercept

(array([[2.0972247 ],
        [0.96708614]], dtype=float32),
 array([-1.2847152], dtype=float32))

In [15]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [16]:
def prediction_function(age, affordibility):
  weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
  return sigmoid(weighted_sum)

In [17]:
prediction_function(.47,1)

0.6610700814679283

In [18]:
prediction_function(0.18,1)

0.5149633892586367

In [24]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true * np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [25]:
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [45]:
class myNN:
  def __init__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0

  def fit(self, X, y, epochs, loss_thresold):
    self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold )

  def predict(self, X_test):
    weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias

    return sigmoid_numpy(weighted_sum)

  def gradient_descent(self, age, affordability, y_true, epochs, loss_thresold):
      #w1, w2 , bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
      weighted_sum = w1 * age + w2 * affordability + bias
      y_predicted = sigmoid_numpy(weighted_sum)

      loss = log_loss(y_true, y_predicted)

      w1d = (1/n)*np.dot(np.transpose(age), (y_predicted-y_true))
      w2d = (1/n)*np.dot(np.transpose(affordability), (y_predicted-y_true))

      bias_d = np.mean(y_predicted-y_true)

      w1 = w1 - rate * w1d
      w2 = w2 - rate * w2d
      bias = bias - rate * bias_d

      if i%50 == 0:
        print(f'Epoch: {i}, w1: {w1}, w2:{w2}, bias:{bias}, loss:{loss}')


      if loss <= loss_thresold:
        print(f'Epoch: {i}, w1: {w1}, w2:{w2}, bias:{bias}, loss:{loss}')
        
        break
      
    return w1, w2, bias

  

In [46]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs= 500 , loss_thresold = 0.4631)

Epoch: 0, w1: 0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch: 50, w1: 1.5033195541731388, w2:1.108384790367645, bias:-1.2319047301235464, loss:0.5675865113475955
Epoch: 100, w1: 2.200713131760032, w2:1.2941584023238903, bias:-1.6607009122062801, loss:0.5390680417774752
Epoch: 150, w1: 2.8495727769689085, w2:1.3696895491572747, bias:-1.986105845859897, loss:0.5176462164249294
Epoch: 200, w1: 3.443016970881804, w2:1.404221862446503, bias:-2.2571369883752723, loss:0.5005011269691375
Epoch: 250, w1: 3.982450494649577, w2:1.423912732932123, bias:-2.494377365971801, loss:0.48654089537617085
Epoch: 300, w1: 4.4721795220959155, w2:1.438787986553552, bias:-2.7073878119223735, loss:0.47508146406327934
Epoch: 350, w1: 4.917245868007634, w2:1.4525660781176122, bias:-2.901176333556766, loss:0.46561475306999006
Epoch: 366, w1: 5.051047623653049, w2:1.4569794548473887, bias:-2.9596534546250037, loss:0.46293944095888917


In [47]:
coef, intercept

(array([[2.0972247 ],
        [0.96708614]], dtype=float32),
 array([-1.2847152], dtype=float32))

In [48]:
customModel.predict(X_test_scaled)

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64

In [49]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 19ms/step


array([[0.6610701 ],
       [0.51496345],
       [0.32312733],
       [0.56699324],
       [0.67040366],
       [0.7234577 ]], dtype=float32)